language: node_js
node_js:
  - '0.12'
sudo: false
env:
  global:
    - secure: ThqRUywTY7BjlTnNXe5d1gElGgVCoXVzHptN/0UWLNI7JYsyX2VoQ/P75iTR28XTZRqUJnnLOMlKfBzqP5r6z4BVfl3fjCa3y5IW9bKFGhEM9mFodtkBnvbnw0R2U4Xdk9KG/WK+5CDo05q+e5OPyRGDl7DosBWamFyjpWWaXtM=
install:
  - bash ./scripts/travis_install.sh
script:
  - bash ./scripts/travis_script.sh
after_success:
  - bash ./scripts/travis_after_success.sh
