language: node_js
node_js:
  - '0.12'
sudo: false
env:
  global:
    - secure: Zv6POtOhi0kIMgvGnt3dGouLc+hXeajKuoBMUPLdYdkeD/JLhNHyZyZkF7SKKeKcVSCUj8Y20hcWH2rErRckvGO3jUdeupUZN5DnwKnFZ2QXF4/s7+xzSR5jbS5IUbL9YVPoxSXMyK7VtkcGa1M4H/1cZYOdSUIz51pkfXipgus=
before_install:
  - chmod +x ./scripts/travis_install.sh
  - chmod +x ./scripts/travis_script.sh
  - chmod +x ./scripts/travis_after_success.sh
install:
  - ./scripts/travis_install.sh
script:
  - ./scripts/travis_script.sh
after_success:
  - ./scripts/travis_after_success.sh
