language: node_js
branches:
  except:master
node_js:
  - '0.12'
sudo: false
script:
    - # this will actually never be run, this is the master branch, which is deployed on gh=pages
    - # in case it still runs, don't make it fail
    - true

