language: node_js
node_js:
  - '0.12'
sudo: false
env:
  global:
    # Matthias token for phosphorjs/phosphorjs.github.io
    - secure: "IhE0iXr0JHBYLPdRrhEYp3VX30EoJYMSxqbpyOuRYaRZQFv1wmTtEdhEuE1j76tPK8LvsTjgdVs3KqoRdt71gs+LT8jjzf1NYMH2prUt8k4cdcu8vmwISGiCkdXUb+2HoBdYG9lS59U72OZOI+wPIAOwDfLhn2MZO2htHbonKd8="
before_install:
  - chmod +x ./scripts/travis_install.sh
  - chmod +x ./scripts/travis_script.sh
  - chmod +x ./scripts/travis_after_success.sh
install:
  - ./scripts/travis_install.sh
script:
  - ./scripts/travis_script.sh
after_success:
  - ./scripts/travis_after_success.sh
